### ISSUE TITLE
formatting the db map when running a database on a non-standard port

### ISSUE THREAD

**Issue by ludwinas** [luminus-framework/jdbc-ring-session#5]
I ran into this situation recently where I ran a postgres database on a non-standard port. I got a `org.postgresql.util.PSQLException: FATAL: password authentication failed for user` when I tried defining my db map like this:

```
(def db
   {:subprotocol "postgresql"
   :subname "session"
   :port "5433"
   :user "admin"
   :password "admin"})
```

So I went and read the [clojure.java.jdbc source](https://github.com/clojure/java.jdbc/blob/master/src/main/clojure/clojure/java/jdbc.clj#L195), which suggests to use this other format, when the port needs to be specified:

```
DriverManager (alternative):
    :dbtype      (required) a String, the type of the database (the jdbc subprotocol)
    :dbname      (required) a String, the name of the database
    :host        (optional) a String, the host name/IP of the database
                            (defaults to 127.0.0.1)
    :port        (optional) a Long, the port of the database
                            (defaults to 3306 for mysql, 1433 for mssql/jtds, else nil)
    (others)     (optional) passed to the driver as properties.
```

Maybe it's worth adding to the README? Since it initially presented itself as an _authentication failed_ error it took me a good while to figure it out.

**Comment by yogthos** [comment]
yeah that sounds reasonable to add an example for that since the error is misleading

**Comment by yogthos** [comment]
@ludwinas could you update the readme with an example config that worked for you? :)

**Comment by ludwinas** [comment]
@yogthos sure :) I'll get to it

**Comment by yogthos** [comment]
:+1:

**Comment by ludwinas** [comment]
Just opened PR #7 about it!

**Comment by yogthos** [comment]
thanks, this will definitely be helpful for reference :)
